In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim) # 2
print(a.dtype) # int32
print(a.shape) # (3,3)
print(a.size) # 9

2
int32
(3, 3)
9


In [6]:
a = np.zeros((2,3))
print(a)

b = np.ones((2,1))
print(b)

# 원소값 초기화하지 않은 배열
# 원소에는 매우크거나 작은값이 들어감
c = np.empty((2,2))
print(c)

d = np.arange(10,30,5)
print(d)

# 똑같은 값4 가진 행렬
e = np.full((2,2),4)
print(e)

f = np.eye(3) # 3*3 단위행렬
print(f)

# 임의값 가진 배열
# 0~1 사이의 값
g = np.random.random((2,2))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]]
[[2.12199579e-314 4.67296746e-307]
 [7.92481296e-321 1.15436571e-311]]
[10 15 20 25]
[[4 4]
 [4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.70309859 0.119731  ]
 [0.90784194 0.69499756]]


In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.random.uniform((3,3))

array([2.81389403, 1.13995658])

In [12]:
np.random.rand(3,3)
# np.random.rand((3,3))는 또 오류...!!

array([[0.87330007, 0.25927983, 0.04037109],
       [0.799851  , 0.56479205, 0.33269782],
       [0.585749  , 0.48979935, 0.6448085 ]])

In [14]:
np.random.random((3,3))
# np.random.random(3,3)는 또 오류... !!

array([[0.43854409, 0.0416425 , 0.2245824 ],
       [0.33654102, 0.45441451, 0.40158981],
       [0.56656936, 0.79382385, 0.67297457]])

In [16]:
np.random.randint(3,5,2)

array([3, 3])

In [17]:
np.random.randint(3,10, (2,3))

array([[8, 5, 7],
       [5, 3, 8]])

In [19]:
# 균등분포 (uniform)
print(np.random.random((2,3)))
print(np.random.rand(3,2))
print()

# 정규분포 (가우시안)
print(np.random.normal(0,1,(2,2)))
print(np.random.normal(3.0,2.0,(2,3)))
print()

# 표준정규분포
print(np.random.randn(2,3))
print(np.random.standard_normal((2,3)))

[[0.91772006 0.98988958 0.70728971]
 [0.13836384 0.31765364 0.79820205]]
[[0.93058496 0.1542653 ]
 [0.21013841 0.29237919]
 [0.03038489 0.26917738]]

[[ 1.37937946  1.17687144]
 [-0.6680541   1.29772562]]
[[3.11811201 1.32785933 0.78754623]
 [2.95767109 2.69909217 2.95498908]]

[[ 2.33209882  0.06269413  0.4326412 ]
 [-1.60838017 -0.04580082  0.6427789 ]]
[[ 0.44353985 -0.79102664  1.30628219]
 [ 0.13152031  2.26252384 -0.32281795]]


# 넘파이 기본 연산

In [20]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(a+b)
print(np.add(a,b))
print()

print(b-a)
print(np.subtract(b,a))
print()

print(a**2)
print()

print(b < 15)
print()

c = np.array([[1,2],[3,4]])
d = np.array([[10,20],[30,10]])

print(c*d) # 원소별 곱셈
print(np.dot(c,d)) # 내적 (dot product)
print(c.dot(d))

[11 22 33]
[11 22 33]

[ 9 18 27]
[ 9 18 27]

[1 4 9]

[ True False False]

[[10 40]
 [90 40]]
[[ 70  40]
 [150 100]]
[[ 70  40]
 [150 100]]


In [21]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [1,3,5,7]])
    
print(a.sum(axis=0))
# 열 기준 덧셈

print(a.sum(axis=1))
# 행 기준 덧셈

print(a.max(axis=1))
# 각 행에서의 최대값

print(a.max(axis=0))
# 각 열에서의 최대값

[ 7 11 15 19]
[10 26 16]
[4 8 7]
[5 6 7 8]


In [22]:
# reduce_sum 은 텐서플로우 것!
a.reduce_sum(axis=0)

AttributeError: 'numpy.ndarray' object has no attribute 'reduce_sum'

# 넘파이 배열 형태 변환

In [25]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

print(a.ravel()) # 원본 변경 
# 1차원 배열로 만들어준다.
print(a.flatten()) # 원본 변경 x
print()
             
print(a.reshape(2,6))
print()

print(a.T)
print(a.transpose())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [27]:
b = a.ravel()
c = a.flatten()

c[0] = 100
print(c)
print(a)
b[0] = 200
print(b)
print(a) # 원본이 변경된 모습

[100   2   3   4   5   6   7   8   9  10  11  12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[200   2   3   4   5   6   7   8   9  10  11  12]
[[200   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [28]:
print(a.reshape(3,-1))

[[200   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


# 넘파이 브로드캐스팅
- 다른 형태의 배열끼리도 연산이 가능하도록 해줌. 
    - 반복문을 사용하지 않고도 

In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,0,1])
y = np.empty_like(a) # 배열 a와 크기가 같은 원소가 비어있는 배열 생성
print(y)
print()

# 배열 b를 a의 각 행에 더해주기 위해 반복문 사용
for i in range(3):
    y[i,:] = a[i,:] + b
print(y)

[[4128860 6029375 3801155]
 [5570652 6619251 7536754]
 [6357084 7536750 7078007]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [30]:
"""
위와 같은 방법은 배열이 커질수록 매우 느려짐. 
--> 브로드캐스팅 사용해서 반복문 없이
"""

c = a+b
print(c)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
